--GET ALL USERS
SELECT USER_ID, NAME, EMAIL, PASSWORD, ADDRESS, REG_DATE, PHONE, UPLOAD_PHOTO FROM PORTAL_USER;

--GET CONTACTS OF USER ANNIE
SELECT PO.NAME, CO.NAME AS CONTACT_NAME, CO.EMAIL, CO.MESSAGE FROM CONTACT CO INNER JOIN PORTAL_USER PO ON  CO.USER_ID=PO.USER_ID WHERE PO.USER_ID='ANNIE';

--GET FEEDBACKS OF USER ANNIE
SELECT FE.NAME, FE.EMAIL, FE.FEEDBACK FROM FEEDBACK FE WHERE FE.USER_ID='ANNIE';

--GET ALL ADMINS
SELECT ADMIN_ID, NAME, EMAIL, PASSWORD FROM ADMIN;

--GET ALL COURSES
SELECT COURSE_ID, COURSE_NAME, COURSE_RESOURCE, COURSE_DESC, COURSE_FEE FROM COURSE;

--GET ALL COURSES CREATED BY ADMIN STEPHER
SELECT COURSE_ID, COURSE_NAME, COURSE_RESOURCE, COURSE_DESC, COURSE_FEE FROM COURSE WHERE ADMIN_ID='STEPHEN';

--GET ALL COURSES ASSIGNED FOR ANNIE
SELECT CO.COURSE_NAME, CO.COURSE_DESC, CO.COURSE_FEE FROM COURSE CO INNER JOIN USER_COURSE UC ON UC.COURSE_ID=CO.COURSE_ID WHERE UC.USER_ID='ANNIE' ;

--GET ALL COURSES COMPLETED BY ANNIE
SELECT CO.COURSE_NAME, CO.COURSE_DESC, CO.COURSE_FEE FROM COURSE CO INNER JOIN USER_COURSE UC ON UC.COURSE_ID=CO.COURSE_ID WHERE UC.USER_ID='ANNIE' AND UC.STATUS='COMPLETED';