INSERT INTO PORTAL_USER (USER_ID, NAME, EMAIL, PASSWORD, ADDRESS, REG_DATE, PHONE, UPLOAD_PHOTO) VALUES('ANNIE','Annie Esther Wilson', 'annie@mars.com', 'test123', 'Waukesha, WI', '04/10/2022', 1234567890, '/test/test.jpg');

INSERT INTO CONTACT (CONTACT_ID, USER_ID, NAME, EMAIL, MESSAGE, PHONE) VALUES('THOMAS','ANNIE', 'Thomas A','Thomas@gmail.com', 'friend', 1234567890);
INSERT INTO CONTACT (CONTACT_ID, USER_ID, NAME, EMAIL, MESSAGE, PHONE) VALUES('VICTOR','ANNIE', 'Victor P','Victor@gmail.com', 'relative', 1234567890);

INSERT INTO FEEDBACK (FEEDBACK_ID, USER_ID, NAME, EMAIL, FEEDBACK) VALUES('FEED_001','ANNIE', 'Annie Esther Wilson','annie@mars.com', 'Course navigation is not user friendly');
INSERT INTO FEEDBACK (FEEDBACK_ID, USER_ID, NAME, EMAIL, FEEDBACK) VALUES('FEED_002','ANNIE', 'Annie Esther Wilson','annie@mars.com', 'Test Feedback');

INSERT INTO ADMIN(ADMIN_ID, NAME, EMAIL, PASSWORD) VALUES('STEPHEN', 'Stephen T', 'stephen@mars.com', 'testpass');

INSERT INTO COURSE(COURSE_ID, ADMIN_ID, COURSE_NAME, COURSE_RESOURCE, COURSE_DESC, COURSE_FEE) VALUES ('COURSE_01', 'STEPHEN', 'JAVA_01', '/test/test.pdf', 'Basic Java Training', '200');
INSERT INTO COURSE(COURSE_ID, ADMIN_ID, COURSE_NAME, COURSE_RESOURCE, COURSE_DESC, COURSE_FEE) VALUES ('COURSE_02', 'STEPHEN', 'WEB_01', '/test/test.pdf', 'Web Training', '250');


INSERT INTO USER_COURSE(COURSE_ID, USER_ID, STATUS) VALUES ('COURSE_01','ANNIE', 'ENROLLED');
INSERT INTO USER_COURSE(COURSE_ID, USER_ID, STATUS) VALUES ('COURSE_02','ANNIE', 'COMPLETED');
